name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
#   - uses: actions/checkout@v1
    - name: configure
      run: curl https://gitlab.cee.redhat.com/identity-management/ipa-pytests/raw/RHEL8.1/metadata/pytests/external-ca.yaml
#   - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
