name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: echo "Hello" + ${{ github.event.number }} 
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}  
#   - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
